### ISSUE TITLE
Donne moi une image et une ligne de commande, je lance le script

### ISSUE THREAD

**Issue by MichaelTSS** [marmakoide/redoutable#1]

**Comment by marmakoide** [comment]
python redoutable.py -u ton-username-reddit -p ton-mot-de-passe -x 42 -y 56 http://i.imgur.com/lzLQQap.png

L'image peut-etre un fichier sur ton ordinateur, ou une URL vers une image. Vois avec les autres sur Reddit et Discord pour savoir quoi mettre ou. Cette ligne de commande est un exemple.
